[build]
    external_node_modules = ["express"]
    node_bundler = "esbuild"
    functions = "/netlify/functions"
    command = "npm --workspace backend run build"
[context.production.environment]
    ENV = "PROD"
    PORT = "3001"
    SECRET_KEY = "m>!%Hz{pB7iM`!,{nE>yft]^@Z%dm="  
    DATABASE_NAME = "hosstess"
    DATABASE_URI = "mongodb+srv://hosstess:u1piHxtM8XkQqSri@hosstess.ol2dhj7.mongodb.net/?retryWrites=true&w=majority&appName=hosstess"
[[redirects]]
    force = true
    from = "/usuarios/*"
    status = 200
    to = "/.netlify/functions/usuarios/:splat"
[[redirects]]
    force = true
    from = "/mesas/*"
    status = 200
    to = "/.netlify/functions/mesas/:splat"